service_name: gateway-service
env: docker
version: dev

log_level: info
shutdown_timeout: 10s

http:
  port: 8083
  timeout: 5s

http_tls:
  enabled: true
  cert_file: /app/certs/gateway-server.crt
  key_file: /app/certs/gateway-server.key


catalog_grpc:
  addr: catalog-service:9091
  timeout: 3s

auth_grpc:
  addr: auth-service:44044
  timeout: 3s

auth_tls:
  enabled: true
  ca_file: /app/certs/ca.crt
  server_name: auth-service
  client_cert_file: /app/certs/gateway-client.crt
  client_key_file: /app/certs/gateway-client.key


otlp:
  endpoint: jaeger:4317

swagger:
  ui_path: /app/web/swagger/index.html
  spec_path: /app/openapi/gateway.v1.yaml

template_path: /app/web/status/index.html